
"use client";

import { useState, useEffect } from "react";
import Image from "next/image";
import { ChevronLeft, ChevronRight, Loader2 } from "lucide-react";
import { cn } from "@/lib/utils";

interface FeaturedImage {
    id: string;
    originalUrl: string;
    basicUrl: string;
    advancedUrl: string;
    user?: { email?: string };
}

export function FeaturedCarousel() {
    const [images, setImages] = useState<FeaturedImage[]>([]);
    const [loading, setLoading] = useState(true);
    const [currentIndex, setCurrentIndex] = useState(0);
    const [compareMode, setCompareMode] = useState<"original" | "basic" | "advanced">("advanced");

    useEffect(() => {
        fetch("/api/featured-images")
            .then(res => res.json())
            .then(data => {
                if (data.images) setImages(data.images);
            })
            .catch(err => console.error("Failed to load featured images", err))
            .finally(() => setLoading(false));
    }, []);

    const nextSlide = () => {
        setCurrentIndex((prev) => (prev + 1) % images.length);
    };

    const prevSlide = () => {
        setCurrentIndex((prev) => (prev - 1 + images.length) % images.length);
    };

    if (loading) return <div className="h-96 flex items-center justify-center"><Loader2 className="w-8 h-8 animate-spin text-purple-600" /></div>;
    if (images.length === 0) return null; // Or return a default static fallback if preferred

    const currentImage = images[currentIndex];
    const displayUrl = compareMode === "original" ? currentImage.originalUrl : compareMode === "basic" ? currentImage.basicUrl : currentImage.advancedUrl;

    return (
        <div className="relative w-full max-w-5xl mx-auto">
            {/* Main Image Display */}
            <div className="relative aspect-[4/3] w-full bg-gray-900 rounded-2xl overflow-hidden shadow-2xl border border-gray-800">
                <Image
                    src={displayUrl}
                    alt={`Featured Generation ${currentIndex + 1} - ${compareMode}`}
                    fill
                    className="object-contain select-none"
                    draggable={false}
                    onDragStart={(e) => e.preventDefault()}
                    onContextMenu={(e) => e.preventDefault()}
                    style={{ userSelect: 'none', WebkitUserSelect: 'none' }}
                />

                {/* Compare Tabs */}
                <div className="absolute bottom-6 left-1/2 -translate-x-1/2 flex bg-black/50 backdrop-blur-md p-1 rounded-xl border border-white/10">
                    <button
                        onClick={() => setCompareMode("original")}
                        className={cn("px-4 py-2 rounded-lg text-sm font-bold transition-all", compareMode === "original" ? "bg-white text-black" : "text-white/70 hover:text-white")}
                    >
                        Original
                    </button>
                    <button
                        onClick={() => setCompareMode("basic")}
                        className={cn("px-4 py-2 rounded-lg text-sm font-bold transition-all", compareMode === "basic" ? "bg-white text-black" : "text-white/70 hover:text-white")}
                    >
                        Basic
                    </button>
                    <button
                        onClick={() => setCompareMode("advanced")}
                        className={cn("px-4 py-2 rounded-lg text-sm font-bold transition-all", compareMode === "advanced" ? "bg-purple-500 text-white" : "text-white/70 hover:text-white")}
                    >
                        Advanced
                    </button>
                </div>

                {/* Navigation Arrows */}
                {images.length > 1 && (
                    <>
                        <button
                            onClick={prevSlide}
                            className="absolute left-4 top-1/2 -translate-y-1/2 p-3 bg-black/30 hover:bg-black/50 text-white rounded-full backdrop-blur-sm transition-all"
                        >
                            <ChevronLeft className="w-6 h-6" />
                        </button>
                        <button
                            onClick={nextSlide}
                            className="absolute right-4 top-1/2 -translate-y-1/2 p-3 bg-black/30 hover:bg-black/50 text-white rounded-full backdrop-blur-sm transition-all"
                        >
                            <ChevronRight className="w-6 h-6" />
                        </button>
                    </>
                )}

                {/* Metadata Overlay (Optional) */}
                {/* <div className="absolute top-4 right-4 bg-black/40 backdrop-blur px-3 py-1 rounded-full text-white/80 text-xs">
                    Generated by Client
                </div> */}
            </div>

            {/* Pagination Dots */}
            {images.length > 1 && (
                <div className="flex justify-center gap-2 mt-4">
                    {images.map((_, idx) => (
                        <button
                            key={idx}
                            onClick={() => setCurrentIndex(idx)}
                            className={cn("w-2 h-2 rounded-full transition-all", idx === currentIndex ? "bg-purple-600 w-6" : "bg-gray-300")}
                        />
                    ))}
                </div>
            )}
        </div>
    );
}
