import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-white text-gray-900 font-sans py-12 px-6">
            <div className="max-w-3xl mx-auto space-y-8">
                <Link href="/" className="inline-flex items-center gap-2 text-purple-600 font-bold hover:underline">
                    <ArrowLeft className="w-4 h-4" />
                    Back to Home
                </Link>

                <h1 className="text-3xl font-extrabold text-gray-900 border-b pb-4">Terms of Service & Disclaimer</h1>

                <div className="space-y-8 text-gray-700 leading-relaxed">
                    <section className="space-y-3">
                        <h2 className="text-xl font-bold text-gray-900 flex items-center gap-2">
                            <span className="text-red-600">1. NO Medical Advice (Critical)</span>
                        </h2>
                        <div className="p-4 bg-red-50 text-red-800 rounded-xl border border-red-100 font-medium">
                            <p>The images generated by this service are for <strong>entertainment purposes only</strong>. They must <strong>NEVER</strong> be used for medical diagnosis, screening, or determining the health status of a fetus. This AI cannot detect deformities, abnormalities, or any medical conditions.</p>
                        </div>
                    </section>

                    <section className="space-y-3">
                        <h2 className="text-xl font-bold text-gray-900">2. Accuracy Disclaimer</h2>
                        <p>
                            CrystalReveal™ AI uses advanced machine learning to predict and visualize a realistic baby face based on 3D ultrasound inputs. However, because ultrasounds often have shadows, occlusions (placenta, umbilical cord, hands), or noise, the AI <strong>&quot;hallucinates&quot; or imagines details</strong> to fill in the missing gaps.
                        </p>
                        <p>
                            Therefore, the generated image may look different from the actual baby. Features like eye shape, nose structure, or specific expressions are AI-generated predictions and not medically accurate reconstructions.
                        </p>
                    </section>

                    <section className="space-y-3">
                        <h2 className="text-xl font-bold text-gray-900">3. Limitation of Liability</h2>
                        <p>
                            By using this service, you acknowledge that Humanscape US Inc. and its affiliates are <strong>not liable</strong> for any emotional, psychological, or physical damages arising from the use of these images. You agree not to make any medical decisions based on these results.
                        </p>
                    </section>

                    <section className="space-y-3">
                        <h2 className="text-xl font-bold text-gray-900">4. Data Usage for Service Improvement</h2>
                        <p>To provide you with the best possible results, we may use uploaded images to:</p>
                        <ul className="list-disc pl-5 space-y-1">
                            <li>Process and deliver your requested AI restoration.</li>
                            <li>Analyze and improve the accuracy, quality, and performance of our AI models.</li>
                            <li>Debug technical issues and prevent errors.</li>
                        </ul>
                        <p className="text-sm bg-gray-50 p-3 rounded-lg border border-gray-100 mt-2">
                            All data used for these purposes is <strong>strictly de-identified (anonymized)</strong> to protect your privacy. We do not sell your personal data.
                        </p>
                    </section>

                    <section className="space-y-3">
                        <h2 className="text-xl font-bold text-gray-900">5. Privacy & California Residents</h2>
                        <p>
                            We collect and process your uploaded images solely to provide the restoration service and strictly for the research purposes stated above. We do not sell your personal information or biometric data to third parties. If you wish to request the deletion of your data from our servers, please contact us at the email below.
                        </p>
                    </section>

                    <div className="pt-8 border-t space-y-2">
                        <p className="text-sm text-gray-500 font-medium">Last Updated: January 2026</p>
                        <p className="text-sm text-gray-500">Contact: <a href="mailto:us_help@humanscape.io" className="text-purple-600 hover:underline">us_help@humanscape.io</a></p>
                    </div>
                </div>
            </div>
        </div>
    );
}
